import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root = fileURLToPath(new URL('../dist/', import.meta.url));
const portfolio = 'https://portfolio-noe-zeta.vercel.app/';
const esc = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const contact = (name, topic='Quiero conocer') => `mailto:support@noeapps.com?subject=${encodeURIComponent(`${topic} ${name}`)}`;
const entries = [
 {name:'ForgeOps',slug:'forgeops',group:'apps',label:'Mantenimiento industrial',status:'Demo disponible',code:'FO',lead:'El mantenimiento de tu planta, bajo control.',description:'Organiza activos, órdenes de trabajo y mantenimiento preventivo desde un mismo espacio.',features:['Activos y equipos con su información de mantenimiento.','Órdenes de trabajo para organizar la actividad del equipo.','Planificación del mantenimiento preventivo y seguimiento de indicadores.'],access:'Explora el recorrido de demostración para conocer el producto. Para valorar su encaje en tu planta, solicita una presentación.',cta:'Ver demo',url:'https://forgeops.eu/demo'},
 {name:'DeleteGuard',slug:'deleteguard',group:'apps',label:'Administración de Jira',status:'En revisión en Marketplace',code:'DG',lead:'Una incidencia se elimina. Su contexto sigue disponible.',description:'Consulta el historial de incidencias eliminadas y quién realizó cada eliminación en Jira Cloud.',image:'/assets/deleteguard.png',existing:true},
 {name:'Fivaki',slug:'fivaki',group:'apps',label:'Hábitos y bienestar',status:'Beta Android',code:'FI',lead:'Dale continuidad a tus hábitos.',description:'Una app que combina seguimiento de hábitos, actividad y progreso con una experiencia gamificada.',features:['Seguimiento de hábitos y objetivos personales.','Una experiencia gamificada para acompañar el progreso.','Versión beta para Android, con información de acceso en su web.'],access:'Fivaki está en beta. La web del proyecto reúne la información de la prueba y la descarga para Android. La versión para iOS todavía no está disponible.',cta:'Conocer la beta',url:'https://fivaki-landing-beta.vercel.app/'},
 {name:'Pequeño Comercio',slug:'pequeno-comercio',group:'apps',label:'Gestión de negocios',status:'Demo en validación',code:'PC',lead:'Menos hojas sueltas. Más visión de tu negocio.',description:'Un proyecto de gestión para reunir ventas, inventario y la operativa de un pequeño comercio.',features:['Gestión de productos e inventario.','Registro de ventas y seguimiento del negocio.','Un espacio de trabajo orientado al día a día del comercio.'],access:'La demo está en validación. Solicita una presentación para explorar sus funciones y comentar las necesidades de tu negocio.',cta:'Solicitar demo'},
 {name:'Quitar Fondo',slug:'quitar-fondo',group:'herramientas',label:'Imagen',status:'Acceso bajo solicitud',code:'01',lead:'Aísla el protagonista de tus imágenes.',description:'Una utilidad de escritorio para eliminar el fondo de una imagen y preparar el resultado.',features:['Selección de imágenes desde una interfaz de escritorio.','Eliminación automática del fondo.','Preparación de imágenes para composiciones y materiales visuales.'],access:'Solicita acceso para consultar la versión disponible y los requisitos de instalación. La herramienta se utiliza en el equipo; esta ficha no recibe imágenes.',cta:'Solicitar acceso'},
 {name:'Texto a Audio',slug:'texto-audio',group:'herramientas',label:'Voz y contenido',status:'Acceso bajo solicitud',code:'02',lead:'Pasa del texto a la voz.',description:'Convierte texto en audio desde una aplicación de escritorio con reproducción integrada.',features:['Conversión de texto a voz.','Controles de reproducción desde la interfaz.','Un flujo sencillo para escuchar contenidos escritos.'],access:'Solicita acceso para consultar los requisitos y opciones disponibles. La conversión utiliza un servicio de voz en línea; revisaremos su encaje si trabajas con texto confidencial.',cta:'Solicitar acceso'},
 {name:'Descargas multimedia',slug:'descargas-multimedia',group:'herramientas',label:'Audio y vídeo',status:'Acceso bajo solicitud',code:'03',lead:'Organiza tus descargas de audio y vídeo.',description:'Una herramienta local para consultar información multimedia y guardar contenido propio o autorizado.',features:['Consulta de información de un vídeo a partir de su dirección.','Descarga de audio o vídeo con las opciones disponibles.','Selección y apertura de la ubicación de descarga.'],access:'Solicita acceso para revisar las fuentes compatibles y la instalación. Utilízala con contenido propio o para el que tengas permiso de descarga.',cta:'Solicitar acceso'},
 {name:'IAgentes',slug:'iagentes',group:'herramientas',label:'Agentes de IA',status:'Prototipo',code:'04',lead:'Explora cómo colaboran los agentes de IA.',description:'Un prototipo para experimentar con conversaciones y configurar instrucciones para agentes.',features:['Interfaz para enviar mensajes y recibir respuestas.','Configuración de instrucciones de los agentes.','Base experimental para estudiar asistentes adaptados a una tarea.'],access:'Está disponible para estudiar una demo y posibles adaptaciones. Requiere configurar el proveedor de IA; las condiciones de uso se acuerdan antes de dar acceso.',cta:'Consultar una demo'},
 {name:'Automatizaciones n8n',slug:'automatizaciones-n8n',group:'herramientas',label:'Flujos de trabajo',status:'Consulta personalizada',code:'05',lead:'Conecta pasos. Recupera tiempo.',description:'Una colección de referencias y flujos para explorar automatizaciones adaptadas a tus procesos.',features:['Selección de flujos por necesidad y herramientas utilizadas.','Revisión de las conexiones y datos que requiere cada proceso.','Adaptación y validación de una propuesta antes de ponerla en marcha.'],access:'Cuéntame qué tarea quieres automatizar. La colección contiene recursos de la comunidad y de terceros; cada propuesta debe respetar la autoría y la licencia de los componentes utilizados.',cta:'Consultar automatización'},
 {name:'TuAnuncio',slug:'tuanuncio',group:'proyectos',label:'Publicidad exterior',status:'Demo conceptual',code:'TA',lead:'Explora una experiencia de publicidad exterior.',description:'Un proyecto para presentar ubicaciones publicitarias y facilitar la consulta de campañas.',features:['Presentación de espacios publicitarios en una experiencia web.','Navegación orientada a explorar ubicaciones y campañas.','Un ejemplo de producto digital para el sector de publicidad exterior.'],access:'La demo utiliza ubicaciones ilustrativas. Sirve para conocer el concepto; no confirma disponibilidad real ni permite contratar o pagar una campaña.',cta:'Ver el proyecto',url:'https://tuanuncio-carretera.noeperezblanco1992.chatgpt.site/'},
 {name:'TuGTA',slug:'tugta',group:'proyectos',label:'Medio digital',status:'Web disponible',code:'TG',lead:'Un espacio para seguir el universo GTA.',description:'Una web editorial dedicada a noticias y contenidos del mundo de Grand Theft Auto.',features:['Publicación y organización de contenidos de actualidad.','Una experiencia centrada en la lectura y el descubrimiento.','Un proyecto independiente de medio digital.'],access:'Puedes visitar la web pública. Es un proyecto independiente, sin afiliación con los titulares de la saga.',cta:'Visitar TuGTA',url:'https://tugta.es/'},
 {name:'Noticias TCG',slug:'noticias-tcg',group:'proyectos',label:'Cartas coleccionables',status:'Web disponible',code:'TC',lead:'Actualidad para quienes disfrutan los TCG.',description:'Un portal de noticias y consulta de información sobre cartas y juegos coleccionables.',features:['Contenidos sobre el mundo de los juegos de cartas.','Consulta de información de cartas y referencias de precios.','Un proyecto que reúne contenido y exploración en una misma web.'],access:'La web se puede visitar públicamente. Las referencias de precios pueden variar y no constituyen una oferta de compraventa.',cta:'Visitar la web',url:'https://noticias-tcg.vercel.app/'},
 {name:'ITFlow Manager',slug:'itflow-manager',group:'proyectos',label:'Operaciones IT',status:'Proyecto de portfolio',code:'IT',lead:'Organiza el trabajo de soporte y mantenimiento IT.',description:'Un proyecto de gestión de servicios IT para explorar la organización del soporte y sus recursos.',features:['Gestión orientada al soporte y mantenimiento de sistemas.','Un entorno de trabajo para estudiar procesos de servicio IT.','Caso de portfolio sobre aplicaciones de gestión.'],access:'Consulta una presentación del proyecto y sus posibilidades de adaptación. No hay una edición comercial abierta desde esta página.',cta:'Conocer el proyecto'},
 {name:'OpsDesk',slug:'opsdesk',group:'proyectos',label:'Service Desk',status:'Prototipo funcional',code:'OD',lead:'Del primer aviso al seguimiento de la incidencia.',description:'Un Service Desk con tickets, asignación, comentarios, histórico de actividad y métricas.',features:['Alta y seguimiento de incidencias con estado y prioridad.','Asignación, comentarios e histórico de actividad.','Indicadores para observar la carga y el avance del trabajo.'],access:'Es un proyecto demostrativo de operaciones IT. Solicita una presentación para conocer el flujo y comentar posibles adaptaciones.',cta:'Solicitar presentación'},
 {name:'EduLabOps',slug:'edulabops',group:'proyectos',label:'Laboratorio de software',status:'Laboratorio',code:'EL',lead:'Un laboratorio para estudiar aplicaciones en operación.',description:'Un proyecto técnico para explorar servicios, tareas en segundo plano y observación de su actividad.',features:['Servicios y procesos que trabajan de forma coordinada.','Tareas en segundo plano y seguimiento de su ejecución.','Un entorno demostrativo para aprender y evaluar decisiones técnicas.'],access:'Consulta el proyecto si te interesa conocer su arquitectura o una demostración guiada.',cta:'Consultar el laboratorio'},
 {name:'Laboratorio industrial',slug:'laboratorio-industrial',group:'proyectos',label:'Industria · IT/OT',status:'Simulación',code:'OT',lead:'De la señal de una máquina al panel de control.',description:'Un laboratorio que conecta señales industriales simuladas con un histórico y un panel de supervisión.',features:['Simulación de señales de máquina, estados y alarmas.','Recogida y almacenamiento de datos industriales.','Visualización de la información en un panel web.'],access:'El entorno utiliza señales simuladas. Solicita una presentación para estudiar el recorrido de los datos y su posible aplicación a un caso real.',cta:'Consultar el laboratorio'}
];
const groupNames = {apps:'Productos',herramientas:'Herramientas',proyectos:'Proyectos'};
const urlOf = e => `/${e.group}/${e.slug}/`;
const nav = `<nav aria-label="Principal"><a href="/#productos">Productos</a><a href="/#herramientas">Herramientas</a><a href="/#proyectos">Proyectos</a><a class="nav-portfolio" href="${portfolio}">Quién soy <span aria-hidden="true">↗</span></a><a href="/soporte/">Soporte</a></nav>`;
const header = `<header class="site-header wrap"><a class="brand" href="/" aria-label="NoeApps, inicio">Noe<span>Apps</span><span class="brand-mark" aria-hidden="true">/</span></a>${nav}</header>`;
const footer = `<footer class="site-footer wrap"><a class="brand small" href="/">Noe<span>Apps</span></a><p>© 2026 Noé Pérez Blanco</p><div><a href="${portfolio}">Quién soy ↗</a><a href="/aviso-legal/">Aviso legal</a><a href="/privacidad/">Privacidad de la web</a><a href="/soporte/">Soporte</a></div></footer>`;
const page = (title,description,route,body) => `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — NoeApps</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow"><meta name="theme-color" content="#102b49"><link rel="canonical" href="https://noeapps.com${route}"><meta property="og:title" content="${esc(title)} — NoeApps"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="https://noeapps.com${route}"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/catalog.css"></head><body><a class="skip-link" href="#contenido">Ir al contenido</a>${header}<main id="contenido" class="wrap">${body}</main>${footer}</body></html>\n`;
const writePage = (route,html) => {const dest=path.join(root,route,'index.html');fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,html);};
const card = e => `<article class="catalog-card ${e.group==='apps'?'product-card':''} ${e.slug==='forgeops'?'card-featured':''}"><div class="card-top"><span class="catalog-mark" aria-hidden="true">${e.image?`<img src="${e.image}" alt="" width="64" height="64" loading="lazy">`:e.code}</span><span class="status">${esc(e.status)}</span></div><p class="card-label">${esc(e.label)}</p><h3><a href="${urlOf(e)}">${esc(e.name)}</a></h3><p class="card-description">${esc(e.description)}</p><a class="card-link" href="${urlOf(e)}" aria-label="Conocer ${esc(e.name)}">Conocer ${e.group==='apps'?'el producto':e.group==='herramientas'?'la herramienta':'el proyecto'} <span aria-hidden="true">↗</span></a></article>`;

const intro = `<section class="hub-hero" id="apps"><div><p class="eyebrow">EL UNIVERSO NOEAPPS</p><h1>Software útil.<br>Todo en un lugar<span class="teal-dot">.</span></h1><p class="hub-lead">Aplicaciones para tu trabajo, herramientas para crear y proyectos para explorar. Hechos por Noé Pérez Blanco.</p><div class="hero-actions"><a class="button button-dark" href="#productos">Explorar productos <span aria-hidden="true">↓</span></a><a class="text-link" href="${portfolio}">Quién soy ↗</a></div></div><aside class="hub-index" aria-label="Explora el catálogo"><p class="eyebrow">ENCUENTRA TU PRÓXIMA HERRAMIENTA</p><a href="#productos"><span>01</span><strong>Productos</strong><span>4 ↗</span></a><a href="#herramientas"><span>02</span><strong>Herramientas</strong><span>5 ↗</span></a><a href="#proyectos"><span>03</span><strong>Proyectos</strong><span>7 ↗</span></a><p>Descubre cada propuesta, consulta su disponibilidad y elige cómo empezar.</p></aside></section>`;
const section = (group,id,number,title,description) => `<section class="catalog-section" id="${id}"><div class="section-heading"><div><p class="eyebrow">${number} / ${groupNames[group].toUpperCase()}</p><h2>${title}</h2></div><p>${description}</p></div><div class="catalog-grid grid-${group}">${entries.filter(e=>e.group===group).map(card).join('')}</div></section>`;
writePage('/',page('Productos, herramientas y proyectos','Descubre ForgeOps, DeleteGuard, Fivaki y las herramientas y proyectos de Noé Pérez Blanco. Demos, acceso y soporte en un mismo lugar.','/',intro+
section('apps','productos','01','Soluciones con un propósito.','Mantenimiento industrial, administración de Jira, hábitos y gestión de pequeños negocios.')+
section('herramientas','herramientas','02','Pequeñas tareas. Más posibilidades.','Imagen, voz, descargas, agentes de IA y automatizaciones. Consulta cada herramienta para solicitar acceso.')+
section('proyectos','proyectos','03','Ideas llevadas a la práctica.','Una selección de webs, prototipos y laboratorios. Cada ficha indica si puedes visitarlo o solicitar una presentación.')+
`<section class="contact-band"><div><p class="eyebrow">¿TIENES UN CASO EN MENTE?</p><h2>Hablemos de lo que necesitas.</h2><p>Cuéntame qué quieres resolver y qué herramienta te interesa.</p></div><a class="button button-light" href="${contact('un proyecto de NoeApps')}">Contactar <span aria-hidden="true">↗</span></a></section><section class="about" id="acerca"><p class="eyebrow">DETRÁS DE NOEAPPS</p><div><h2>Soy Noé Pérez Blanco.</h2><p>Desarrollo software y trabajo en la conexión entre sistemas, procesos y personas. NoeApps es el punto de encuentro de mis productos y proyectos; en mi portfolio puedes conocer mi trayectoria y mi trabajo en entornos IT e industriales.</p><a class="text-link" href="${portfolio}">Quién soy · Ver mi portfolio ↗</a></div></section>`));

for(const e of entries.filter(e=>!e.existing)){
 const href=e.url || contact(e.name,e.cta);
 const body=`<nav class="breadcrumb" aria-label="Ruta de navegación"><a href="/">NoeApps</a><span aria-hidden="true">/</span><a href="/#${e.group==='apps'?'productos':e.group}">${groupNames[e.group]}</a><span aria-hidden="true">/</span><span aria-current="page">${esc(e.name)}</span></nav><section class="detail-hero"><p class="eyebrow">${esc(e.label)}</p><span class="status">${esc(e.status)}</span><h1>${esc(e.name)}</h1><p class="detail-lead">${esc(e.lead)}</p><p class="detail-description">${esc(e.description)}</p><div class="hero-actions"><a class="button button-dark" href="${esc(href)}">${esc(e.cta)} <span aria-hidden="true">↗</span></a><a class="text-link" href="/soporte/">Tengo una consulta</a></div></section><div class="detail-layout"><section class="detail-features"><h2>Qué puedes explorar</h2><ol>${e.features.map((f,i)=>`<li><span aria-hidden="true">0${i+1}</span><p>${esc(f)}</p></li>`).join('')}</ol></section><aside class="access-panel"><p class="eyebrow">DISPONIBILIDAD</p><h2>${esc(e.status)}</h2><p>${esc(e.access)}</p>${!e.url?'<p class="access-note">La consulta abre tu correo. El acceso y las condiciones se acuerdan directamente antes de compartir la herramienta.</p>':''}<a class="text-link" href="${esc(href)}">${esc(e.cta)} ↗</a></aside></div><section class="more-catalog"><h2>Sigue explorando</h2><div>${entries.filter(x=>x.group===e.group&&x.slug!==e.slug).slice(0,3).map(x=>`<a href="${urlOf(x)}">${esc(x.name)} <span aria-hidden="true">↗</span></a>`).join('')}</div><a class="text-link" href="/#${e.group==='apps'?'productos':e.group}">Ver ${groupNames[e.group].toLowerCase()}</a></section>`;
 writePage(urlOf(e),page(e.name,e.description,urlOf(e),body));
}

// Keep the established contractual documents intact; refresh shared navigation only.
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(x=>x.isDirectory()?walk(path.join(d,x.name)):[path.join(d,x.name)]);
for(const f of walk(root).filter(x=>x.endsWith('.html'))){
 let html=fs.readFileSync(f,'utf8');
 html=html.replace(/<header class="site-header wrap">[\s\S]*?<\/header>/,header).replace(/<footer class="site-footer wrap">[\s\S]*?<\/footer>/,footer);
 if(!html.includes('href="/catalog.css"'))html=html.replace('</head>','<link rel="stylesheet" href="/catalog.css"></head>');
 if(f===path.join(root,'apps','deleteguard','index.html')){
  html=html.replaceAll('En preparación','En revisión en Marketplace').replace('Esta página presenta la versión que estamos preparando.','La versión presentada está pendiente de la revisión de Atlassian.').replace('Versión en preparación.','Versión en revisión.');
  html=html.replace('content="noindex,nofollow"','content="index,follow"');
  if(!html.includes('rel="canonical"'))html=html.replace('</head>','<link rel="canonical" href="https://noeapps.com/apps/deleteguard/"></head>');
 }
 if(f===path.join(root,'soporte','index.html')&&!html.includes('id="acceso-herramientas"'))html=html.replace('<h2>Contacto</h2>',`<h2 id="acceso-herramientas">Demos y acceso a herramientas</h2><p>Las fichas de <a href="/#productos">productos</a>, <a href="/#herramientas">herramientas</a> y <a href="/#proyectos">proyectos</a> indican su disponibilidad. Puedes solicitar una demo o consultar el acceso escribiendo a support@noeapps.com. Indica el nombre y el uso que tienes en mente para concretar las condiciones.</p><h2>Contacto</h2>`);
 fs.writeFileSync(f,html);
}
const routes=['/',...entries.map(urlOf)];
fs.writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(r=>`<url><loc>https://noeapps.com${r}</loc></url>`).join('')}</urlset>\n`);
fs.writeFileSync(path.join(root,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: https://noeapps.com/sitemap.xml\n');
console.log(JSON.stringify({catalogEntries:entries.length,productPages:4,tools:5,projects:7,sitemapRoutes:routes.length}));
